config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tlks#index'

  get '/tlk/:id', to: 'tlks#show', as: 'show_tlk'
  resources :tlks, only: [:new, :create]
  resources :messages, only: :create
  # resources :tlks do
  #   resources :messages, shallow: true
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :participant
  belongs_to :user
  belongs_to :tlk
  has_rich_text :content

  def create
    Message.create!(message_params)
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :tlk
  belongs_to :user
  has_many :messages
end

app/models/tlk.rb
class Tlk < ApplicationRecord
  belongs_to :user
  has_many :participants
  has_many :messages

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :title,
      [:title, DateTime.now.to_date]
    ]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tlks
  has_many :participants
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = Message.new(message_params)
    message.user = current_user
    message.save!
    tlk = Tlk.friendly.find(params['message']['tlk_id'])
    redirect_to "/tlk/#{tlk[:slug]}"
  end

  private

  def message_params
    params.require(:message).permit(:content, :tlk_id, :participant_id)
  end
end

app/controllers/tlks_controller.rb
class TlksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @tlks = Tlk.includes(:participants)
  end

  def show
    @tlk = Tlk.includes(:participants, :messages).friendly.find(params[:id])
    @user_participants = Participant.where(tlk: @tlk, user: current_user)
    @message = Message.new()
  end

  def new
    @tlk = Tlk.new()
  end

  def create
    @tlk = Tlk.new(tlk_params)
    @tlk.user = current_user
    @tlk.save!
    create_self_participant
    create_external_participants
    redirect_to "/tlk/#{@tlk.slug}"
  end

  private

  def tlk_params
    params.require(:tlk).permit(:title, :description)
  end

  def create_self_participant
    self_params = params.require(:tlk).permit(:name, :bio)
    participant = Participant.new(self_params)
    participant.user = current_user
    participant.email = current_user.email
    participant.pending = false
    participant.tlk = @tlk
    participant.save!
  end

  def create_external_participants
    @p_email = params.require(:tlk).permit(:p_email)[:p_email]
    if User.find_by_email(@p_email)
      # ParticipantMailer.with(tlk: @tlk).unregistered_participant.deliver_later
      puts "nothing"
    else
      # ParticipantsMailer.with(tlk: @tlk, p_email: @p_email).unregistered_participant.deliver_now
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tlks_helper.rb
module TlksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaaalkApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to "Taaalk", root_path, class: "navbar-brand" %>

  <%= link_to "Start a Taaalk", new_tlk_path %>
  <% if user_signed_in? %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</nav>

app/views/tlks/index.html.erb
<h1>Taaalk</h1>
<h2>Description of The Taaalk Co.</h2>

<% @tlks.each do |tlk| %>
  <%= link_to show_tlk_path(tlk) do %>
    <h4><%= tlk.title %></h4>
    <% tlk.participants.each do |p| %>
      <p><%= p.name %></p>
    <% end %>
    <p><%= tlk.description %></p>
  <% end %>
<% end %>

app/views/tlks/new.html.erb
<h1>hello!</h1>

<%= form_with model: @tlk do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <h2>Your own details for the Taaalk</h2>
  <p>You can customise your details for each Taaalk.</p>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, value: current_user.username %>
  </div>
  <div class="field">
    <%= form.label :bio %>
    <p>Make sure your bio matches up to what this Taaalk is about.</p>
    <%= form.text_field :bio, value: current_user.bio %>
  </div>
  <h2>Who are you Taaalking with?</h2>
  <p>(Optional. You can have a monologue if you want.)</p>
  <div class="field">
    <%= form.label :p_email %>
    <%= form.email_field :p_email %>
    <p>Note to josh: I can use the title and description for the email content.</p>
  </div>
  <%= form.submit %>

<% end %>

<!-- 1. invite another user with an email address -->
<!-- 2. invite a user who you are 'friends' with already -->
<!-- 3. invite a current user who is not your friend and make friend request -->

app/views/tlks/show.html.erb
<h1><%= @tlk.title %></h1>
<h2><%= @tlk.description %></h2>
<% @tlk.participants.each do |p| %>
  <h3><%= p.name %></h3>
  <p><%= p.bio %></p>
<% end %>

<% @tlk.messages.each do |msg| %>
  <p><%= msg.participant.name %></p>
  <p><%= msg.content %></p>
<% end %>

<% @user_participants.each do |participant| %>
  <%= form_with model: @message do |form| %>
    <div class="field">
      <%= form.label :content %>
      <%= form.rich_text_area :content %>
    </div>
    <%= form.hidden_field :tlk_id, :value => @tlk.id %>
    <%= form.hidden_field :participant_id, :value => participant.id %>
    <%= form.submit %>
  <% end %>
<% end %>